### ISSUE TITLE
Clear session file if parsing json content triggers exception

### ISSUE THREAD

**Issue by giovannizorzato** [valery-barysok/session-file-store#36]
If session file is being written while restarting node process, it may become corrupted.
I suggest to clear the session file if JSON.parse triggers exception and to return a "null" session

**Comment by valery-barysok** [comment]
@giovannizorzato, thanks. I will think about it. You can contribute with your fix. In other case it will take some undefined time.
Before last version your case could not be resolved because session has been written and read concurrently and you could not distinct corrupted session from partially written.
But now it writes session to temp file and then just rename it. So I guess fix can be very simple.

**Comment by valery-barysok** [comment]
If you use latest version then this issue is not relevant now (so i close this issue) else correct me if i am wrong.
